SEED_SUPPLIERS_DATA = [
    {'supplier_name': 'TechSource Nexus', 'location': 'Mumbai', 'contact_email': 'contact@techsourcenexus.com', 'reliability_score': 8.7},
    {'supplier_name': 'Digital Forge', 'location': 'Bangalore', 'contact_email': 'contact@digitalforge.com', 'reliability_score': 9.2},
    {'supplier_name': 'ElectroWave Systems', 'location': 'Chennai', 'contact_email': 'contact@electrowavesystems.com', 'reliability_score': 8.9},
    {'supplier_name': 'Circuit Boulevard', 'location': 'Mumbai', 'contact_email': 'contact@circuitboulevard.com', 'reliability_score': 8.4},
    {'supplier_name': 'Apex Laptops', 'location': 'Bangalore', 'contact_email': 'contact@apexlaptops.com', 'reliability_score': 9.1},
    {'supplier_name': 'Mobile Horizon', 'location': 'Chennai', 'contact_email': 'contact@mobilehorizon.com', 'reliability_score': 8.6},
    {'supplier_name': 'SoundVision Studio', 'location': 'Mumbai', 'contact_email': 'contact@soundvisionstudio.com', 'reliability_score': 9.3},
    {'supplier_name': 'Silicon Valley Warehouse', 'location': 'Bangalore', 'contact_email': 'contact@siliconvalleywarehouse.com', 'reliability_score': 7.8},
    {'supplier_name': 'LinkStream Tech', 'location': 'Chennai', 'contact_email': 'contact@linkstreamtech.com', 'reliability_score': 8.5},
    {'supplier_name': 'SmartEdge Wholesale', 'location': 'Mumbai', 'contact_email': 'contact@smartedgewholesale.com', 'reliability_score': 9.0},
]

SEED_PRODUCTS_DATA = [
    # Computers & Accessories
    {'product_name': 'Dell OptiPlex Desktop', 'category': 'Desktop Computers', 'unit_price': 45000.00, 'supplier_id': 1},
    {'product_name': 'HP Pavilion Desktop', 'category': 'Desktop Computers', 'unit_price': 42000.00, 'supplier_id': 8},
    {'product_name': 'Lenovo ThinkCentre Desktop', 'category': 'Desktop Computers', 'unit_price': 48000.00, 'supplier_id': 1},
    {'product_name': 'Lenovo Legion Gaming Laptop', 'category': 'Laptop Computers', 'unit_price': 85000.00, 'supplier_id': 5},
    {'product_name': 'Lenovo ThinkPad Business Laptop', 'category': 'Laptop Computers', 'unit_price': 75000.00, 'supplier_id': 1},
    {'product_name': 'HP Pavilion Laptop', 'category': 'Laptop Computers', 'unit_price': 55000.00, 'supplier_id': 10},
    {'product_name': 'Dell Inspiron Laptop', 'category': 'Laptop Computers', 'unit_price': 52000.00, 'supplier_id': 5},
    {'product_name': 'Samsung 24" LED Monitor', 'category': 'Computer Monitors', 'unit_price': 12000.00, 'supplier_id': 1},
    {'product_name': 'LG 27" LCD Monitor', 'category': 'Computer Monitors', 'unit_price': 15000.00, 'supplier_id': 8},
    {'product_name': 'Dell 32" LED Monitor', 'category': 'Computer Monitors', 'unit_price': 22000.00, 'supplier_id': 1},
    {'product_name': 'Logitech Wireless Keyboard', 'category': 'Wireless Keyboards', 'unit_price': 1500.00, 'supplier_id': 1},
    {'product_name': 'Microsoft Wireless Keyboard', 'category': 'Wireless Keyboards', 'unit_price': 1800.00, 'supplier_id': 8},
    {'product_name': 'HP Wireless Keyboard', 'category': 'Wireless Keyboards', 'unit_price': 1200.00, 'supplier_id': 10},
    {'product_name': 'Logitech Wireless Mouse', 'category': 'Wireless Mice', 'unit_price': 800.00, 'supplier_id': 1},
    {'product_name': 'Microsoft Wireless Mouse', 'category': 'Wireless Mice', 'unit_price': 1000.00, 'supplier_id': 8},
    {'product_name': 'HP Wireless Mouse', 'category': 'Wireless Mice', 'unit_price': 700.00, 'supplier_id': 10},
    {'product_name': 'Lenovo 65W Laptop Charger', 'category': 'Laptop Chargers', 'unit_price': 1500.00, 'supplier_id': 5},
    {'product_name': 'HP 90W Laptop Charger', 'category': 'Laptop Chargers', 'unit_price': 1800.00, 'supplier_id': 5},
    {'product_name': 'Dell 45W Laptop Charger', 'category': 'Laptop Chargers', 'unit_price': 1400.00, 'supplier_id': 5},
    {'product_name': 'Seagate 1TB External HDD', 'category': 'External Hard Drives', 'unit_price': 3500.00, 'supplier_id': 2},
    {'product_name': 'Western Digital 2TB External HDD', 'category': 'External Hard Drives', 'unit_price': 5500.00, 'supplier_id': 2},
    {'product_name': 'Toshiba 1TB External HDD', 'category': 'External Hard Drives', 'unit_price': 3200.00, 'supplier_id': 2},
    {'product_name': 'Samsung 256GB SSD', 'category': 'SSD Drives', 'unit_price': 3000.00, 'supplier_id': 2},
    {'product_name': 'Kingston 512GB SSD', 'category': 'SSD Drives', 'unit_price': 5000.00, 'supplier_id': 8},
    {'product_name': 'Crucial 1TB SSD', 'category': 'SSD Drives', 'unit_price': 8500.00, 'supplier_id': 2},
    {'product_name': 'Corsair 8GB DDR4 RAM', 'category': 'RAM Modules', 'unit_price': 2500.00, 'supplier_id': 2},
    {'product_name': 'Kingston 16GB DDR4 RAM', 'category': 'RAM Modules', 'unit_price': 4500.00, 'supplier_id': 8},
    {'product_name': 'G.Skill 8GB DDR4 RAM', 'category': 'RAM Modules', 'unit_price': 2300.00, 'supplier_id': 2},
    {'product_name': 'Logitech C270 Webcam', 'category': 'Webcams', 'unit_price': 2500.00, 'supplier_id': 2},
    {'product_name': 'Microsoft LifeCam Webcam', 'category': 'Webcams', 'unit_price': 3000.00, 'supplier_id': 2},
    
    # Networking Equipment
    {'product_name': 'TP-Link AC1750 Router', 'category': 'WiFi Routers', 'unit_price': 3500.00, 'supplier_id': 3},
    {'product_name': 'Netgear Nighthawk Router', 'category': 'WiFi Routers', 'unit_price': 8500.00, 'supplier_id': 9},
    {'product_name': 'ASUS RT-AX Router', 'category': 'WiFi Routers', 'unit_price': 12000.00, 'supplier_id': 3},
    {'product_name': 'Cisco 8-Port Switch', 'category': 'Network Switches', 'unit_price': 4500.00, 'supplier_id': 3},
    {'product_name': 'TP-Link 16-Port Switch', 'category': 'Network Switches', 'unit_price': 7500.00, 'supplier_id': 9},
    {'product_name': 'Netgear 5-Port Switch', 'category': 'Network Switches', 'unit_price': 2500.00, 'supplier_id': 3},
    {'product_name': 'AmazonBasics Cat6 Cable 10ft', 'category': 'Ethernet Cables', 'unit_price': 300.00, 'supplier_id': 3},
    {'product_name': 'Cable Matters Cat6 Cable 25ft', 'category': 'Ethernet Cables', 'unit_price': 600.00, 'supplier_id': 9},
    {'product_name': 'Monoprice Cat6 Cable 50ft', 'category': 'Ethernet Cables', 'unit_price': 1000.00, 'supplier_id': 3},
    {'product_name': 'Motorola Cable Modem', 'category': 'Modems', 'unit_price': 3500.00, 'supplier_id': 3},
    {'product_name': 'ARRIS SURFboard Modem', 'category': 'Modems', 'unit_price': 4500.00, 'supplier_id': 3},
    {'product_name': 'TP-Link WiFi Extender', 'category': 'Range Extenders', 'unit_price': 2000.00, 'supplier_id': 3},
    {'product_name': 'Netgear WiFi Range Extender', 'category': 'Range Extenders', 'unit_price': 2500.00, 'supplier_id': 3},
    
    # Mobile & Tablets
    {'product_name': 'Samsung Galaxy S23', 'category': 'Smartphones', 'unit_price': 65000.00, 'supplier_id': 6},
    {'product_name': 'iPhone 14', 'category': 'Smartphones', 'unit_price': 75000.00, 'supplier_id': 1},
    {'product_name': 'Google Pixel 7', 'category': 'Smartphones', 'unit_price': 55000.00, 'supplier_id': 10},
    {'product_name': 'OnePlus 11', 'category': 'Smartphones', 'unit_price': 58000.00, 'supplier_id': 6},
    {'product_name': 'iPad Air', 'category': 'Tablets', 'unit_price': 55000.00, 'supplier_id': 1},
    {'product_name': 'Samsung Galaxy Tab S8', 'category': 'Tablets', 'unit_price': 48000.00, 'supplier_id': 6},
    {'product_name': 'Microsoft Surface Go', 'category': 'Tablets', 'unit_price': 42000.00, 'supplier_id': 10},
    {'product_name': 'Spigen iPhone Case', 'category': 'Phone Cases', 'unit_price': 800.00, 'supplier_id': 6},
    {'product_name': 'OtterBox Samsung Case', 'category': 'Phone Cases', 'unit_price': 1200.00, 'supplier_id': 6},
    {'product_name': 'UAG Rugged Case', 'category': 'Phone Cases', 'unit_price': 1500.00, 'supplier_id': 6},
    {'product_name': 'ZAGG Tempered Glass', 'category': 'Screen Protectors', 'unit_price': 500.00, 'supplier_id': 6},
    {'product_name': 'amFilm Screen Protector', 'category': 'Screen Protectors', 'unit_price': 300.00, 'supplier_id': 6},
    {'product_name': 'Anker 10000mAh Power Bank', 'category': 'Power Banks', 'unit_price': 1500.00, 'supplier_id': 6},
    {'product_name': 'RAVPower 20000mAh Power Bank', 'category': 'Power Banks', 'unit_price': 2500.00, 'supplier_id': 10},
    {'product_name': 'Xiaomi 5000mAh Power Bank', 'category': 'Power Banks', 'unit_price': 1000.00, 'supplier_id': 6},
    
    # Audio & Video
    {'product_name': 'Sony WH-1000XM5 Headphones', 'category': 'Bluetooth Headphones', 'unit_price': 28000.00, 'supplier_id': 7},
    {'product_name': 'Bose QuietComfort Headphones', 'category': 'Bluetooth Headphones', 'unit_price': 32000.00, 'supplier_id': 7},
    {'product_name': 'Sennheiser HD Headphones', 'category': 'Bluetooth Headphones', 'unit_price': 25000.00, 'supplier_id': 7},
    {'product_name': 'Apple AirPods Pro', 'category': 'Wireless Earbuds', 'unit_price': 22000.00, 'supplier_id': 6},
    {'product_name': 'Samsung Galaxy Buds', 'category': 'Wireless Earbuds', 'unit_price': 12000.00, 'supplier_id': 7},
    {'product_name': 'Jabra Elite Earbuds', 'category': 'Wireless Earbuds', 'unit_price': 15000.00, 'supplier_id': 6},
    {'product_name': 'Blue Yeti USB Microphone', 'category': 'USB Microphones', 'unit_price': 12000.00, 'supplier_id': 7},
    {'product_name': 'Rode NT-USB Microphone', 'category': 'USB Microphones', 'unit_price': 15000.00, 'supplier_id': 7},
    {'product_name': 'AmazonBasics HDMI Cable 6ft', 'category': 'HDMI Cables', 'unit_price': 400.00, 'supplier_id': 4},
    {'product_name': 'Belkin HDMI Cable 10ft', 'category': 'HDMI Cables', 'unit_price': 600.00, 'supplier_id': 7},
    {'product_name': 'Cable Matters HDMI Cable 15ft', 'category': 'HDMI Cables', 'unit_price': 800.00, 'supplier_id': 9},
    {'product_name': 'JBL Flip 6 Speaker', 'category': 'Speakers', 'unit_price': 10000.00, 'supplier_id': 7},
    {'product_name': 'Bose SoundLink Speaker', 'category': 'Speakers', 'unit_price': 18000.00, 'supplier_id': 7},
    {'product_name': 'Sony SRS Speaker', 'category': 'Speakers', 'unit_price': 8500.00, 'supplier_id': 7},
    
    # Cables & Adapters
    {'product_name': 'Anker USB-C Cable 6ft', 'category': 'USB-C Cables', 'unit_price': 600.00, 'supplier_id': 4},
    {'product_name': 'Belkin USB-C Cable 10ft', 'category': 'USB-C Cables', 'unit_price': 800.00, 'supplier_id': 9},
    {'product_name': 'Cable Matters USB-C Cable 3ft', 'category': 'USB-C Cables', 'unit_price': 400.00, 'supplier_id': 4},
    {'product_name': 'Apple Lightning Cable 3ft', 'category': 'Lightning Cables', 'unit_price': 1500.00, 'supplier_id': 4},
    {'product_name': 'Anker Lightning Cable 6ft', 'category': 'Lightning Cables', 'unit_price': 800.00, 'supplier_id': 4},
    {'product_name': 'Belkin Lightning Cable 10ft', 'category': 'Lightning Cables', 'unit_price': 1000.00, 'supplier_id': 4},
    {'product_name': 'Cable Matters HDMI to VGA Adapter', 'category': 'HDMI to VGA Adapters', 'unit_price': 800.00, 'supplier_id': 4},
    {'product_name': 'Benfei HDMI to VGA Adapter', 'category': 'HDMI to VGA Adapters', 'unit_price': 600.00, 'supplier_id': 4},
    {'product_name': 'Anker 4-Port USB Hub', 'category': 'USB Hubs', 'unit_price': 1200.00, 'supplier_id': 4},
    {'product_name': 'Sabrent 7-Port USB Hub', 'category': 'USB Hubs', 'unit_price': 1800.00, 'supplier_id': 4},
    {'product_name': 'TP-Link 10-Port USB Hub', 'category': 'USB Hubs', 'unit_price': 2500.00, 'supplier_id': 4},
    {'product_name': 'Apple Lightning to 3.5mm Adapter', 'category': 'Audio Jack Adapters', 'unit_price': 800.00, 'supplier_id': 4},
    {'product_name': 'Samsung USB-C to 3.5mm Adapter', 'category': 'Audio Jack Adapters', 'unit_price': 500.00, 'supplier_id': 4},
    {'product_name': 'Anker USB-C to 3.5mm Adapter', 'category': 'Audio Jack Adapters', 'unit_price': 400.00, 'supplier_id': 4},
    {'product_name': 'AmazonBasics USB 2.0 Cable', 'category': 'USB Cables', 'unit_price': 200.00, 'supplier_id': 9},
    {'product_name': 'Anker USB 3.0 Cable', 'category': 'USB Cables', 'unit_price': 400.00, 'supplier_id': 9},
    {'product_name': 'Cable Matters USB-A to USB-B Cable', 'category': 'USB Cables', 'unit_price': 300.00, 'supplier_id': 9},
    {'product_name': 'Monoprice HDMI 2.1 Cable', 'category': 'HDMI Cables', 'unit_price': 1000.00, 'supplier_id': 9},
    {'product_name': 'Mediabridge Cat6 Cable', 'category': 'Ethernet Cables', 'unit_price': 500.00, 'supplier_id': 9},
    {'product_name': 'Anker USB Wall Charger', 'category': 'Power Adapters', 'unit_price': 1200.00, 'supplier_id': 4},
    {'product_name': 'Belkin USB-C Wall Charger', 'category': 'Power Adapters', 'unit_price': 1500.00, 'supplier_id': 4},
    {'product_name': 'Cable Matters USB-C to HDMI Adapter', 'category': 'Display Adapters', 'unit_price': 1200.00, 'supplier_id': 4},
    {'product_name': 'StarTech DisplayPort to HDMI Adapter', 'category': 'Display Adapters', 'unit_price': 1500.00, 'supplier_id': 4},
]

SEED_INVENTORY_DATA = [
    # Computers & Accessories (28 products)
    {'product_id': 1, 'quantity': 8},
    {'product_id': 2, 'quantity': 6},
    {'product_id': 3, 'quantity': 5},
    {'product_id': 4, 'quantity': 12},
    {'product_id': 5, 'quantity': 10},
    {'product_id': 6, 'quantity': 15},
    {'product_id': 7, 'quantity': 14},
    {'product_id': 8, 'quantity': 20},
    {'product_id': 9, 'quantity': 18},
    {'product_id': 10, 'quantity': 10},
    {'product_id': 11, 'quantity': 35},
    {'product_id': 12, 'quantity': 30},
    {'product_id': 13, 'quantity': 25},
    {'product_id': 14, 'quantity': 40},
    {'product_id': 15, 'quantity': 38},
    {'product_id': 16, 'quantity': 32},
    {'product_id': 17, 'quantity': 22},
    {'product_id': 18, 'quantity': 20},
    {'product_id': 19, 'quantity': 18},
    {'product_id': 20, 'quantity': 15},
    {'product_id': 21, 'quantity': 12},
    {'product_id': 22, 'quantity': 10},
    {'product_id': 23, 'quantity': 25},
    {'product_id': 24, 'quantity': 20},
    {'product_id': 25, 'quantity': 18},
    {'product_id': 26, 'quantity': 45},
    {'product_id': 27, 'quantity': 40},
    {'product_id': 28, 'quantity': 42},
    {'product_id': 29, 'quantity': 28},
    {'product_id': 30, 'quantity': 25},
    # Networking Equipment (13 products)
    {'product_id': 31, 'quantity': 18},
    {'product_id': 32, 'quantity': 8},
    {'product_id': 33, 'quantity': 6},
    {'product_id': 34, 'quantity': 12},
    {'product_id': 35, 'quantity': 10},
    {'product_id': 36, 'quantity': 15},
    {'product_id': 37, 'quantity': 60},
    {'product_id': 38, 'quantity': 50},
    {'product_id': 39, 'quantity': 45},
    {'product_id': 40, 'quantity': 10},
    {'product_id': 41, 'quantity': 8},
    {'product_id': 42, 'quantity': 20},
    {'product_id': 43, 'quantity': 18},
    # Mobile & Tablets (15 products)
    {'product_id': 44, 'quantity': 15},
    {'product_id': 45, 'quantity': 12},
    {'product_id': 46, 'quantity': 10},
    {'product_id': 47, 'quantity': 14},
    {'product_id': 48, 'quantity': 10},
    {'product_id': 49, 'quantity': 12},
    {'product_id': 50, 'quantity': 8},
    {'product_id': 51, 'quantity': 40},
    {'product_id': 52, 'quantity': 35},
    {'product_id': 53, 'quantity': 30},
    {'product_id': 54, 'quantity': 55},
    {'product_id': 55, 'quantity': 60},
    {'product_id': 56, 'quantity': 35},
    {'product_id': 57, 'quantity': 25},
    {'product_id': 58, 'quantity': 30},
    # Audio & Video (14 products)
    {'product_id': 59, 'quantity': 10},
    {'product_id': 60, 'quantity': 8},
    {'product_id': 61, 'quantity': 12},
    {'product_id': 62, 'quantity': 18},
    {'product_id': 63, 'quantity': 20},
    {'product_id': 64, 'quantity': 15},
    {'product_id': 65, 'quantity': 14},
    {'product_id': 66, 'quantity': 10},
    {'product_id': 67, 'quantity': 50},
    {'product_id': 68, 'quantity': 45},
    {'product_id': 69, 'quantity': 40},
    {'product_id': 70, 'quantity': 22},
    {'product_id': 71, 'quantity': 15},
    {'product_id': 72, 'quantity': 18},
    # Cables & Adapters (23 products)
    {'product_id': 73, 'quantity': 55},
    {'product_id': 74, 'quantity': 50},
    {'product_id': 75, 'quantity': 60},
    {'product_id': 76, 'quantity': 45},
    {'product_id': 77, 'quantity': 50},
    {'product_id': 78, 'quantity': 40},
    {'product_id': 79, 'quantity': 30},
    {'product_id': 80, 'quantity': 28},
    {'product_id': 81, 'quantity': 35},
    {'product_id': 82, 'quantity': 30},
    {'product_id': 83, 'quantity': 25},
    {'product_id': 84, 'quantity': 42},
    {'product_id': 85, 'quantity': 40},
    {'product_id': 86, 'quantity': 38},
    {'product_id': 87, 'quantity': 65},
    {'product_id': 88, 'quantity': 60},
    {'product_id': 89, 'quantity': 55},
    {'product_id': 90, 'quantity': 48},
    {'product_id': 91, 'quantity': 52},
    {'product_id': 92, 'quantity': 45},
    {'product_id': 93, 'quantity': 40},
    {'product_id': 94, 'quantity': 32},
    {'product_id': 95, 'quantity': 30},
]